### ISSUE TITLE
Add a meaningful description to the Readme

### ISSUE THREAD

**Issue by botwithfeelings** [shaowns/PrivacySearchQueries#6]
@arewm, My first attempt at the readme got thwarted because I was not sure about the distinction between the change in search behavior or privacy behavior (or both) among the US population in reaction to the Snowden revelation of Govt. surveillance. 

Anything succinct and to the point would do, can flesh out later if needed. Thanks in advance.

**Comment by arewm** [comment]
This has been completed. The content is the same as the first version of the abstract. Content can later be changed to the paper's introduction.
